export const words = {
  headerTittle: "Shopping Cart",
  mainTittle: "Content",
  footerTittli: " © CopyWrite Amgad Mohamed 2022",
  title: "Title:",
  qty: "Qty:",
  price: "Price: $",
  remove:"Remove",
  total: "Total: ",
  selectBtn:"Select Product",
  orderDoneSuccess:"order done success",
  name:"Name:",
  name2:"email",
  Email:"Email:",
  selectProduct:"Select Product:",
  text:"text",
  email:"email",
  checkout:"Checkout",
  filter: "Filter",
  numberpro: "Number Of Products:",
  ALL: "ALL",
  XS: "XS",
  S: "S",
  M: "M",
  L: "L",
  XL: "XL",
  XXL: "XXL",
  order: "Order",
  Latest: "Latest",
  Lowest: "Lowest",
  Highest: "Highest",
  addToCart:" Add To Cart"
};
